storage:
  mongo:
    username: "cognita"
    password: "cognita"
    host: "mongo"
    port: 27017
    database: "cognita"
  
  redis:
    username: null
    password: "cognita"
    host: "redis"
    port: 6379
    database: 0

plugins:
  root: "/cognita/plugins"
  enabled:
    - plugin-template
    - 5e-plugin