FROM python:3.12.2-alpine

RUN mkdir -p /cognita/cognita_api /cognita/certs
VOLUME /cognita/cognita_api
COPY ./requirements.txt /cognita
COPY ./certs /cognita/certs
COPY ./config.yaml /cognita
WORKDIR /cognita
RUN python -m pip install -r requirements.txt
EXPOSE 8000/tcp

ENTRYPOINT [ "litestar", "--app", "cognita_api:app", "run", "--reload", "--host", "0.0.0.0", "--ssl-certfile", "/cognita/certs/api/cert.pem", "--ssl-keyfile", "/cognita/certs/api/key.pem" ]